application: test
version: 1
runtime: python27
api_version: 1
threadsafe: true

builtins:
- remote_api: on
- deferred: on
- appstats: on

handlers:
- url: /_ah/pipeline(/.*)?
  script: pipeline.handlers._APP

- url: /test/.*
  script: demo.app

- url: /.*
  script: index.app
