application: test
version: 1
runtime: python27
api_version: 1
threadsafe: true
module: BigDataLab

builtins:
- remote_api: on
- deferred: on
- appstats: on

handlers:
- url: /_ah/pipeline(/.*)?
  script: pipeline.handlers._APP

- url: /test/.*
  script: demo.app

- url: /.*
  script: index.app

basic_scaling:
  instance_class: B8
  max_instances: 255
  idle_timeout: 15m
