application: test
version: 1
runtime: python27
api_version: 1
threadsafe: true
module: bigdatalab

builtins:
- remote_api: on
- deferred: on
- appstats: on

libraries:
- name: endpoints
  version: "latest"
- name: jinja2
  version: "latest"

handlers:
- url: /_ah/pipeline(/.*)?
  script: pipeline.handlers._APP

- url: /_ah/spi/.*
  script: apis.app

- url: /index\.html
  static_files: media/index.html
  upload: media/index.html

- url: /test/.*
  script: demo.app

- url: /.*
  script: index.app

instance_class: B1
basic_scaling:
  max_instances: 20
  idle_timeout: 15m
